# -*- coding: utf-8 -*-
"""2. Expression and Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XvBBX4OLsTylNiBX1CGrsWZO1dV_ufbh

# Expressions, Operators, Control statements

# Operators
- Arithmetic (+, -, *, /, //, %)
- Relational (<, >, <=, >=, !=, ==)
- Shift (>>, <<)
- Assignment (=)
- Logical (and, or, not)
- Bitwise (&, |, !)
- 'in' and 'not in' operator

# << and >>

if n=8 (1000 in binary), n>>1 will give 100 after shifting bits by 1 place to right. 
                         n<<1 will give 10000 after shifting bits by 1 place to left.
"""

n=9
print(n,'binary',format(n,'b'))
print(n,'* 2=',n<<1, format(n<<1,'b'))
print(n,'/ 2=',n>>1,format(n>>1,'b'))

# logical
x = True
y = False
print('x and y is',x and y) # Output: x and y is False
print('x or y is',x or y) # Output: x or y is True
print('not x is',not x) # Output: not x is False

# bitwise
x=12 
y=4
print(x & y) 
print(x | y)
print(x ^ y)

# in and not in

x = 'Hello world'
print('H' in x)    # Output: True
print('h' not in x)   # Output: True

# perform operations on complex numbers

import cmath
a=complex(20+5j)
b=complex(5+3j)
print('a+b',a+b)
print('a-b',a-b)
print('a*b',a*b)
print('a/b',a/b)



"""### Task1 Write a program in python to calculate area of triangle when all three sides are given.
- s=(a+b+c)/2
- area =  √(s(s-a)(s-b)(s-c) )
"""

# write your code after this line
import math
length=int(input("Enter lenght of triangle"))
breadth=int(input("Enter Breadth of triangle"))
height=int(input("Enter height of triangle"))
s=(length+breadth+height)/2
area=(s*(s-height)*(s-length)*(s-breadth))
m=abs(area)
areaf=math.sqrt(m)
print(areaf)

"""# Control Statements

### Decisions (if-else)

# simple if-else
if(cond):
    stmt
else:
    stmt

# if-else-if
if(cond):
    stmt
elif(cond):
    stmt
    .
    .
    .
else: 
    stmt

# nested if-else
                            if(cond):
                                stmt
                                if(cond):
                                    stmt1
                            else:
                                if(cond):
                                    stmt3
                                else:
                                    stmt4

### Task2: Write a proram that accept a lowercase/uppercase character from the user and check whether the character is a vowel or consonant.
"""

# write your code after this line
ch=input("Enter a letter ")
if(ch == 'a' or ch == 'e' or ch == 'i' or ch == 'o' or ch == 'u' or ch == 'A'
       or ch == 'E' or ch == 'I' or ch == 'O' or ch == 'U'):
  print("Character entered is Vowel ")
else:
  print("Character is consonant ")

"""### Task3: Write a program to check whether given character is a digit or a character in lowercase or uppercase alphabet. Hint: ASCII value of digit is between 48 to 58 and Lowercase characters in the range of 97 to122, uppercase is between 65 and 90)."""

# write your code after this line
ch=input("Enter a digit(ASCII) or character") 
if (ch>='48' and ch<='58'):
  print("Its a digit")
if(ch>='97' and ch<='122'):
  print("Character is lowercase")
if(ch>='65' and ch<='90'):
  print("Character is uppercase")

"""### Repetition or loop
- while loop
- for loop

#### While loop

initialization of loop variable
while( condition ):
    stmt 1
    stmt 2
    ...
    update loop variable

##### Task 4: Write a program in Python to print table of any number 'n' provided by user using while loop.
"""

# write your code after this line
n = int(input("Enter any number : "))
for i in range(1, 11):
  print(n," x ", i, " = ", n*i)

"""##### Task 5: Write a program in Python to evaluate the following series using while loop:
    
    1! + 2! + 3! + 4! ...+ n!
hint: use math.factorial(n) function to calculate factorial of number n.
"""

import math
Sum=0
j=int(input("enter any number:"))
for i in range(1,j+1):
  fact=math.factorial(i)
  Sum += fact
  
print("sum of series is:", Sum)

# write your code after this line
n, fact = int(input("Enter the number : ")), 1
for i in range(1,n+1):
  fact *= i
print("Factorial        :",fact)

"""##### Task 6: Write a program in Python to enter the numbers till the user wants and at the end it should display the maximum number entered using while loop."""

# write your code after this line
check, l = 'Y', []
while(check == 'Y' or check == 'y'):
  n = int(input("Enter the number : "))
  l.append(n)
  check = input("Do you want to enter more numbers??(Y/N) : ")
  if check == 'N' or check == 'n':
    break

print("Maximum number :", max(l))

"""### for loop

for iterable_var_name in range(terminating_value):
    stmt 1
    stmt 2
    ...
    
 for iterable_var_name in range(initial_value,terminating_value):
    stmt 1
    stmt 2
    ...
    
 for iterable_var_name in range(initial_value,terminating_value,updation):
    stmt 1
    stmt 2
    ...
"""

# factorial
n=int(input('Enter a number '))
fact=1
for i in range(n,1,-1):
    fact=fact*i
print(n,'! =',fact)

"""##### Task 7:Write a program in Python to print all numbers from 0 to 9 except 3 and 6 using a for loop."""

# write your code after this line
for i in range(0, 10):
  if i == 3 or i == 6:
    continue
  else:
    print("Number :", i)

"""#### 2 Write a program in Python to get 10 numbers from user using a for loop. The program should print the count of positive numbers, negative numbers and zeroes entered by the user."""

pos, neg, zero = 0, 0, 0
for i in range(10):
  n = int(input("Enter the number : "))
  if n == 0:
    zero += 1
  elif n < 0:
    neg += 1
  else:
    pos += 1
print("Negative :", neg, "\nPositive :", pos, "\nZero :", zero)